# ==============================================================================
# ⚙️ Apache Oozie — Pipeline Execution Runtime Properties
# ==============================================================================
nameNode=hdfs://hadoop:9000
jobTracker=hadoop:8032
sparkMaster=spark-master
oozie.wf.application.path=${nameNode}/apps/oozie/workflow.xml
oozie.use.system.libpath=true

dbHost=mysql
dbName=retail_db
dbUser=root
dbPass=H@doop2022

inputDir=${nameNode}/data/sqoop/customers
sparkOutputDir=${nameNode}/data/spark/customers_transformed
pigOutputDir=${nameNode}/data/pig/customers_aggregated
